"""empty message

Revision ID: 65cd379f7a23
Revises: 92a72ca5d9e1
Create Date: 2022-06-19 13:34:24.587727

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '65cd379f7a23'
down_revision = '92a72ca5d9e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=True),
    sa.Column('created_on', sa.TIMESTAMP(timezone=True), server_default=sa.text('current_timestamp'), nullable=True),
    sa.Column('updated_on', sa.TIMESTAMP(timezone=True), server_default=sa.text('current_timestamp'), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('href', sa.String(length=25), nullable=False),
    sa.Column('type', sa.String(length=25), nullable=False),
    sa.Column('img_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['img_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artists_created_on'), 'artists', ['created_on'], unique=False)
    op.create_index(op.f('ix_artists_id'), 'artists', ['id'], unique=False)
    # op.alter_column('images', 'id',
    #            existing_type=postgresql.UUID(),
    #            nullable=True,
    #                 primary_key=True,
    #            existing_server_default=sa.text('uuid_generate_v4()'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'id',
               existing_type=postgresql.UUID(),
               nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.drop_index(op.f('ix_artists_id'), table_name='artists')
    op.drop_index(op.f('ix_artists_created_on'), table_name='artists')
    op.drop_table('artists')
    # ### end Alembic commands ###
