"""empty message

Revision ID: c46ad24d146d
Revises: 65cd379f7a23
Create Date: 2022-06-19 14:17:30.004360

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c46ad24d146d'
down_revision = '65cd379f7a23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('artists', 'id',
    #            existing_type=postgresql.UUID(),
    #            nullable=True,
    #            existing_server_default=sa.text('uuid_generate_v4()'))
    # op.alter_column('images', 'id',
    #            existing_type=postgresql.UUID(),
    #            nullable=True,
    #            existing_server_default=sa.text('uuid_generate_v4()'))
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.alter_column('images', 'id',
               existing_type=postgresql.UUID(),
               nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('artists', 'id',
               existing_type=postgresql.UUID(),
               nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    # ### end Alembic commands ###
